INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP )
VALUES(100, 'SALARY', 'EUR', 'Maniek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP )
VALUES(300, 'GOVERNMENT_SUPPORT', 'EUR', 'Maniek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP )
VALUES(500, 'ADHOC_WORK', 'EUR', 'Maniek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP )
VALUES(700, 'RENT', 'EUR', 'Maniek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP, CREATION_TIMESTAMP, UPDATE_TIMESTAMP )
VALUES(800, 'GIFT', 'EUR', 'Maniek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null);